### ISSUE TITLE
Shiraha missing.

### ISSUE THREAD

**Issue by angeldollface** [angeldollface/lume-themes#3]
@kwaa Since I changed the way data is processed now, can you add a `*.markdown` file to the `themes` directory so yours is in? I like it but I don't have all the info.

**Comment by angeldollface** [comment]
I'm not pushing anything further from my side until that is done.

**Comment by angeldollface** [comment]
Take your time. :heart:

**Comment by kwaa** [comment]
I'm getting ready for bed so it might take tomorrow.

Also, I think it would be nice to be able to automatically fetch data from github repo /lume.land since keeping it updated is a hassle.

**Comment by angeldollface** [comment]
For what purpose, though? You sleep well!!! ❤️‍🔥 I think fetching data is overkill. I'm not going to update my themes that often and even if, this project should just guide people towards using some theme. Which is why each page is littered with links to guide a potential user to a repo for that theme. And really, no stress! :heart:

**Comment by angeldollface** [comment]
@kwaa I didn't want to bother you again but we have four themes for now (yours included) on this project so it is better to do it while the number of themes is as small as it is.

**Comment by kwaa** [comment]
Perhaps it would be better suited as part of the lume.land website?

That way don't have to worry about the data.

**Comment by angeldollface** [comment]
i'm not entirely sure what Oscar's plans are, let's see, I guess? Are you still doing it, though? Let#s talk tomorrow. 🙈

**Comment by kwaa** [comment]
OK, continuing the previous discussion.
Whether or not we should merge into the lume.land site / auto-fetch data, I don't think it makes much sense to use markdown files.

> Why?

Theme names and descriptions don't usually change much, but `README.md` does change a lot.
The `*.markdown` file for this repo is an exact duplicate of the `README.md` function.
So when click on "Use Me!", I think you should redirect to the GitHub repo.

**Comment by angeldollface** [comment]
Hope you slept well!❤️ True, for now, they are exact replicas of the repos' `README`s but the thing is that the idea behind changing the data source was that the detail page on our index should be the ***first*** source of info on the theme. The `README` in the respective repo should just complement what's already here, on our index. Your point about having to update info is valid which is why everyone who makes themes should update the info only when they extra info is desperately needed. Minor changes can be documented in a repo's `CHANGELOG`. What do you think?

**Comment by angeldollface** [comment]
@oscarotero What do you think?

**Comment by kwaa** [comment]
In addition, I have opened a PR. #4

**Comment by angeldollface** [comment]
@kwaa Just had a look at your "Shiraha" theme, amazing work! I like it a lot! You're quite talented! And thank you so much for all your PRs.

@oscarotero Agreed, I do too, I just made this yesterday to a) thank you and b) show you my appreciation for all the help you've given me and all the support you've shown me and my Lume projects. Merging this with the main `lume.land` can be done when we all have more time. Plus, I want to be a part of the Lume project, one of the active contributors.

Ad your second point: Maybe but then I'd have to pass it along, because like you, I'm really busy. To whoever wants to do this. We could both ask on Discord who wants to do this? Or do you want to leave it as it is, for now?

I'm closing this issue, because "Shiraha" is now there.
