### ISSUE TITLE
Project Transfer

### ISSUE THREAD

**Issue by angeldollface** [angeldollface/lume-themes#5]
Hi @oscarotero and @kwaa Does anyone of you wanna take this over? I'm too busy and kinda misting out a bit and Oscar, you added a "themes" section anyway, so no need for this now, or? If neither of you wanna take over, I'll remove it.

**Comment by oscarotero** [comment]
Hi @angeldollface 
Thanks for your work creating this (It inspired me to create the "themes" section in lume.land).
I think you can remove it, no need to have two indexes for Lume themes :)

**Comment by angeldollface** [comment]
@oscarotero Should I send you the files or transfer the repo to you for future reference maybe?

**Comment by oscarotero** [comment]
I don't think I need it but I have local clone of the repo just in case.
Thanks!

**Comment by angeldollface** [comment]
Okay, great. I'll delete it then. :)
